# Generated by Django 6.0.3 on 2026-05-21 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Accesorio (huacal)',
                'verbose_name_plural': 'Accesorios (huacales)',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='SOItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_item', models.CharField(max_length=50, unique=True)),
                ('material', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'SO Item',
                'verbose_name_plural': 'SO Items',
                'ordering': ['so_item'],
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('accesorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='Items.accesorio')),
                ('so_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='Items.soitem')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
