# Generated by Django 6.0.3 on 2026-05-21 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesorio',
            options={'ordering': ['codigo'], 'verbose_name': 'Accesorio', 'verbose_name_plural': 'Accesorios'},
        ),
        migrations.AlterField(
            model_name='registro',
            name='accesorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='Items.accesorio'),
        ),
    ]
