# Generated by Django 6.0.3 on 2026-05-22 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Items", "0005_backfill_entradas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DestinatarioAlertaHuacal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nombre", models.CharField(blank=True, max_length=100)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Destinatario de alerta",
                "verbose_name_plural": "Destinatarios de alerta",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="MensajeAlertaHuacal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asunto",
                    models.CharField(
                        default="Alerta: inventario de huacales agotado", max_length=200
                    ),
                ),
                (
                    "cuerpo",
                    models.TextField(
                        default="El inventario de huacales ha llegado a 0.\nEs necesario reabastecer cuanto antes.\n"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de alerta",
                "verbose_name_plural": "Mensaje de alerta",
            },
        ),
        migrations.CreateModel(
            name="StockHuacal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField(default=0)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Stock de huacales",
                "verbose_name_plural": "Stock de huacales",
            },
        ),
        migrations.CreateModel(
            name="MovimientoHuacal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("entrada", "Entrada"), ("salida", "Salida")],
                        max_length=10,
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("saldo_despues", models.IntegerField()),
                ("nota", models.CharField(blank=True, max_length=200)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de huacales",
                "verbose_name_plural": "Movimientos de huacales",
                "ordering": ["-creado"],
            },
        ),
    ]
