# Generated by Django 6.0.3 on 2026-05-22 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Items", "0006_destinatarioalertahuacal_mensajealertahuacal_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConteoHuacal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("cantidad", models.PositiveIntegerField()),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conteo de huacal",
                "verbose_name_plural": "Conteos de huacal",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Huacal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pn", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.CharField(blank=True, max_length=200)),
                ("medidas", models.CharField(blank=True, max_length=50)),
                ("consumo_semanal", models.PositiveIntegerField(default=0)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("pallet", "Pallets"), ("crate", "Crates")],
                        default="pallet",
                        max_length=10,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Huacal",
                "verbose_name_plural": "Huacales",
                "ordering": ["tipo", "pn"],
            },
        ),
        migrations.RemoveField(
            model_name="movimientohuacal",
            name="usuario",
        ),
        migrations.DeleteModel(
            name="StockHuacal",
        ),
        migrations.AddField(
            model_name="conteohuacal",
            name="huacal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conteos",
                to="Items.huacal",
            ),
        ),
        migrations.DeleteModel(
            name="MovimientoHuacal",
        ),
        migrations.AddConstraint(
            model_name="conteohuacal",
            constraint=models.UniqueConstraint(
                fields=("huacal", "fecha"), name="conteo_huacal_fecha_unique"
            ),
        ),
    ]
