# Generated by Django 6.0.3 on 2026-05-22 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Items", "0008_seed_huacales"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrada",
            name="accesorio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entradas",
                to="Items.accesorio",
            ),
        ),
        migrations.AddField(
            model_name="entrada",
            name="huacal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entradas",
                to="Items.huacal",
            ),
        ),
    ]
