# Generated by Django 6.0.3 on 2026-05-22 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Items", "0009_entrada_accesorio_entrada_huacal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entrada",
            name="accesorio",
        ),
    ]
